version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.28
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-107-22-7-9.compute-1.amazonaws.com
            database: d85gne8hl2rbj7
            user: vjetkfcqzvpwra
            password: fb6edbb999c4e2f5ffbdb22a513a87af278d7a4badb2149a1d451061e3e75804
            rawAccess: true
            ssl: true
            port: '5432'
            migrations: true